services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: false

  Tourze\RaffleCoreBundle\Controller\:
    resource: '../../Controller/'
  Tourze\RaffleCoreBundle\Repository\:
    resource: '../../Repository/'
  Tourze\RaffleCoreBundle\Service\:
    resource: '../../Service/'
    public: true
  Tourze\RaffleCoreBundle\EventSubscriber\:
    resource: '../../EventSubscriber/'
    public: true